repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks-docker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck
        # args: ["--severity=warning"]  # Optionally only show errors and warnings
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v0.121.1'
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ['--config', 'p/default', '--error', '--skip-unknown-extensions']